"""sigma2 公共 API。"""

from pyta2.base.schema import Schema
from pyta2.utils.space import Box, Scalar, Space

from .core import (
    forward_signal_apply,
    pyta2_signal,
    rKlineSignal,
    rKlineWindowSignal,
    rOrderBookSignal,
    rPyta2Signal,
    rSignal,
    rTradeSignal,
)
from .kline import (
    KlineATR,
    KlineBoll,
    KlineGap,
    KlineKDJ,
    KlineMA,
    KlineMACD,
    KlineRSI,
    KlineReturn,
    rKlineATR,
    rKlineATRBoundTrigger,
    rKlineBoll,
    rKlineFutureChange,
    rKlineFutureHighLowChange,
    rKlineFutureReturn,
    rKlineGap,
    rKlineKDJ,
    rKlineMA,
    rKlineMACD,
    rKlineRSI,
    rKlineReturn,
)
from .orderbook import rBookSpread
from .trade import rTradeSignedVolume
from .utils import Pyta2Component, register_pyta2_indicator, resolve_pyta2_indicator

__all__ = [
    "Box",
    "KlineATR",
    "KlineBoll",
    "KlineGap",
    "KlineKDJ",
    "KlineMA",
    "KlineMACD",
    "KlineRSI",
    "KlineReturn",
    "Pyta2Component",
    "Scalar",
    "Schema",
    "Space",
    "forward_signal_apply",
    "pyta2_signal",
    "register_pyta2_indicator",
    "resolve_pyta2_indicator",
    "rBookSpread",
    "rKlineATR",
    "rKlineATRBoundTrigger",
    "rKlineBoll",
    "rKlineFutureChange",
    "rKlineFutureHighLowChange",
    "rKlineFutureReturn",
    "rKlineGap",
    "rKlineKDJ",
    "rKlineMA",
    "rKlineMACD",
    "rKlineRSI",
    "rKlineReturn",
    "rKlineSignal",
    "rKlineWindowSignal",
    "rOrderBookSignal",
    "rPyta2Signal",
    "rSignal",
    "rTradeSignal",
    "rTradeSignedVolume",
]
